export const DOCUMENTS_SKILL = [
  "---",
  "name: documents",
  "description: Use this skill when the user asks for a Word document, DOCX file, report, memo, brief, proposal, meeting notes, or another polished document deliverable.",
  "---",
  "",
  "# DeepSeekCode Documents Skill",
  "",
  "Use the runtime document tools instead of creating temporary helper scripts in the artifact directory.",
  "",
  "Workflow:",
  "1. Clarify only when the audience, topic, or output path is missing and cannot be inferred.",
  "2. Gather task-specific source material with read_file, grep_files, browser tools, or MCP tools when the user asks for grounded content or research.",
  "3. Draft concise Markdown with semantic headings, short paragraphs, bullets, and tables where useful.",
  "4. Call create_docx with the final Markdown and target path. For reports, long Chinese documents, or any multiline document over about 1,500 characters, use markdown_lines instead of one huge markdown string.",
  "5. Call validate_artifact with expected_kind docx.",
  "6. If validation fails, revise and recreate the DOCX before finishing.",
  "",
  "Rules:",
  "- Do not write generate_docx.py, generate_docx.js, or any helper script into the user's artifact directory.",
  "- Do not call create_pptx from this documents skill. If slides are also requested, finish the DOCX task and let the parent task invoke the presentations skill.",
  "- Temporary implementation details must stay inside runtime tools or an explicit scratch folder, not beside the final deliverable.",
  "- The final artifact directory should contain the requested document and user-visible companion files only.",
  "- Prefer formal Chinese for Chinese business reports unless the user requests another style.",
  "- Use tables for comparisons, risks, schedules, budgets, and decision logs.",
  "- Prefer markdown_lines for DOCX generation so native tool arguments stay valid and readable.",
  "- Keep claims traceable to inspected files or cited research when the prompt asks for research.",
].join("\n");

export const PRESENTATIONS_SKILL = [
  "---",
  "name: presentations",
  "description: Use this skill when the user asks for a slide deck, PPT, PPTX, presentation, pitch deck, course deck, defense slides, or speaker-note-ready deck.",
  "---",
  "",
  "# DeepSeekCode Presentations Skill",
  "",
  "Use the runtime presentation tools instead of creating temporary helper scripts in the artifact directory.",
  "",
  "Workflow:",
  "1. Identify audience, purpose, duration, topic, and target path from the request.",
  "2. Gather source material first when the user asks to research a subject or base the deck on project files.",
  "3. Build a narrative outline before creating slides: title, problem/background, core concepts, evidence, examples, risks or tradeoffs, summary.",
  "4. If the user gives an explicit slide/page count, plan exactly that many slides total. Do not add an extra title, agenda, Q&A, or closing slide unless it fits inside the requested count.",
  "5. Call create_pptx with structured slides. Use clear slide titles, 3-6 bullets per slide, and a visual hint for diagrams or comparison visuals.",
  "6. Include speaker_notes when the deck is for teaching, defense, training, or executive presentation.",
  "7. Call validate_artifact with expected_kind pptx.",
  "8. If validation fails, revise and recreate the PPTX before finishing.",
  "",
  "Rules:",
  "- Do not write generate_pptx.py, generate_pptx.js, or other helper scripts into the user's artifact directory.",
  "- Do not call create_docx from this presentations skill. If a Word document is also requested, finish the PPTX task and let the parent task invoke the documents skill.",
  "- The final artifact directory should not contain intermediate generation scripts.",
  "- Use diagrams, process visuals, architecture blocks, timelines, or comparison layouts when the user asks for rich visual content.",
  "- Match explicit deck length requirements exactly; a requested 6-page or 6-slide deck means create 6 slides total.",
  "- In create_pptx, slides.length is the normal final slide count. include_title_slide adds one extra cover slide and should stay false for exact-count requests unless the user explicitly allows a separate cover.",
  "- Prefer accurate, grounded content over decorative slides.",
  "- For Chinese decks, use concise Chinese slide text and keep long explanations in speaker notes.",
].join("\n");
