export function buildAgentDashboardOverlay(): { style: string; markup: string; script: string } {
  const style = `<style>
:root{
  --dsc-console-w:clamp(600px,42vw,820px);
  --dsc-ink:#162033;
  --dsc-muted:#607086;
  --dsc-line:#d8e2ef;
  --dsc-blue:#2563eb;
  --dsc-good:#13835b;
  --dsc-warn:#a66a00;
  --dsc-bad:#c43b3b;
}
html,body,#root{width:100%;height:100%;margin:0;overflow:hidden;background:#0f1424!important}
body{font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0}
#root{position:fixed!important;inset:0 var(--dsc-console-w) 0 0!important;width:auto!important;height:auto!important;overflow:hidden!important;opacity:.18;filter:saturate(.75) brightness(.62)}
#root canvas,#root img{image-rendering:pixelated}
#root .absolute.top-8.left-8.z-10,#root .absolute.bottom-10.left-10.z-20,#root .absolute.bottom-8.right-28.z-20,#root [title*="Zoom"],#root [style*="z-index: 41"][style*="pointer-events: none"]{display:none!important}
#dsc-war{position:fixed;inset:0 var(--dsc-console-w) 0 0;z-index:2147482997;color:#edf7ff;display:grid;grid-template-rows:minmax(154px,21vh) minmax(0,1fr) minmax(118px,15vh);gap:14px;padding:18px;background:radial-gradient(circle at 30% 34%,rgba(68,100,132,.24),transparent 34%),linear-gradient(180deg,#171b2d,#0b1020)}
#dsc-war *{box-sizing:border-box}
.dsc-room-card{border:1px solid rgba(196,215,240,.28);background:rgba(10,17,31,.78);box-shadow:0 18px 42px rgba(0,0,0,.34);backdrop-filter:blur(8px);border-radius:8px}
#dsc-board{border:2px solid #9a7337;background:linear-gradient(180deg,#183421,#0b1710);padding:14px 16px;overflow:hidden}
.dsc-board-head{display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:18px;font-weight:900;color:#f4fff2}.dsc-board-head span{font-size:12px;color:#cdebc6}
.dsc-board-progress{height:8px;border-radius:999px;background:rgba(212,242,206,.18);margin:10px 0;overflow:hidden}.dsc-board-progress span{display:block;height:100%;background:linear-gradient(90deg,#8ee68f,#67e8f9);border-radius:999px;transition:width .28s ease}
.dsc-board-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px 14px}.dsc-board-item{min-width:0;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:8px;align-items:center;border-bottom:1px solid rgba(202,235,198,.16);padding:5px 0}.dsc-dot{width:10px;height:10px;border-radius:999px;background:#8b98aa}.dsc-dot.running{background:#60a5fa;box-shadow:0 0 0 4px rgba(96,165,250,.18)}.dsc-dot.succeeded{background:#34d399}.dsc-dot.needs_review{background:#f6bd60}.dsc-dot.blocked,.dsc-dot.failed{background:#fb7185}
.dsc-board-name{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:850}.dsc-board-meta{display:block;margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;color:#b8cabb}.dsc-board-status{font-size:12px;white-space:nowrap;color:#daf7d7}
#dsc-ops{min-height:0;display:grid;grid-template-columns:1.18fr .76fr .76fr;grid-template-rows:1fr 1fr;gap:14px;grid-template-areas:"work dispatch lounge" "work review issue"}
.dsc-zone{position:relative;min-width:0;min-height:0;overflow:hidden;padding:12px}.zone-work{grid-area:work;background:linear-gradient(180deg,rgba(93,60,35,.82),rgba(69,42,25,.82))}.zone-dispatch{grid-area:dispatch;background:linear-gradient(180deg,rgba(34,58,82,.84),rgba(23,39,59,.84))}.zone-lounge{grid-area:lounge;background:linear-gradient(180deg,rgba(45,76,105,.84),rgba(31,55,82,.84))}.zone-review{grid-area:review;background:linear-gradient(180deg,rgba(44,68,68,.84),rgba(27,48,50,.84))}.zone-issue{grid-area:issue;background:linear-gradient(180deg,rgba(87,43,50,.84),rgba(48,25,31,.84))}
.dsc-zone-title{display:flex;justify-content:space-between;gap:8px;font-weight:900;color:#ecf5ff}.dsc-zone-title span{font-size:12px;color:#c7d8ec;font-weight:750}.dsc-zone-grid{position:absolute;inset:46px 12px 12px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));grid-auto-rows:minmax(82px,1fr);gap:10px}.zone-work .dsc-zone-grid{grid-auto-rows:minmax(114px,1fr)}
.dsc-desk,.dsc-seat{border:1px solid rgba(230,241,255,.23);border-radius:8px;background:rgba(4,10,20,.24);position:relative;overflow:hidden}.dsc-desk:before{content:"";position:absolute;left:14%;right:14%;top:18px;height:18px;border-radius:3px;background:#c19a63;box-shadow:0 22px 0 #8c663d}.dsc-seat:before{content:"";position:absolute;left:50%;top:18px;width:54px;height:28px;transform:translateX(-50%);border-radius:8px;background:#b73767;box-shadow:0 34px 0 #8d274d}
.dsc-role{position:absolute;left:10px;right:10px;bottom:8px;border:1px solid rgba(207,225,252,.5);border-radius:8px;background:rgba(16,25,41,.95);padding:8px 10px;box-shadow:0 14px 28px rgba(0,0,0,.3);transition:transform .24s ease,border-color .24s ease}.dsc-role.running{border-color:#60a5fa;animation:dsc-work 1.35s ease-in-out infinite}.dsc-role.blocked,.dsc-role.failed{border-color:#fb7185}.dsc-role.succeeded{border-color:#34d399}.dsc-role-name{display:block;font-size:14px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsc-role-line{display:block;margin-top:3px;font-size:12px;color:#c7d8ec;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsc-role-task{display:block;margin-top:4px;font-size:12px;line-height:1.35;color:#e8f0fb;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
#dsc-feed{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.dsc-feed-card{padding:12px;overflow:hidden}.dsc-feed-card b{display:block;margin-bottom:8px;font-size:13px;color:#f8fbff}.dsc-feed-card span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#c7d6e8;font-size:12px;line-height:1.55}.dsc-pill{display:inline-block!important;width:auto;border:1px solid rgba(103,232,249,.36);border-radius:999px;padding:1px 6px;margin-right:5px;color:#a5f3fc!important}
#dsc-console{position:fixed;right:0;top:0;bottom:0;width:var(--dsc-console-w);z-index:2147482999;background:#f8fafc;color:var(--dsc-ink);border-left:1px solid var(--dsc-line);display:grid;grid-template-rows:auto auto auto minmax(0,1fr) auto;box-shadow:-18px 0 48px rgba(6,14,30,.22)}
#dsc-console *{box-sizing:border-box;letter-spacing:0}.dsc-head{padding:22px 24px 16px;border-bottom:1px solid var(--dsc-line);display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;align-items:start;background:#fff}.dsc-brand{font-size:11px;color:#4f46e5;font-weight:900;text-transform:uppercase}.dsc-title{margin-top:8px;font-size:24px;line-height:1.18;font-weight:900;word-break:break-word}.dsc-collapse{min-width:52px;min-height:44px;border:1px solid var(--dsc-line);border-radius:8px;background:#fff;color:var(--dsc-ink);font-weight:800;cursor:pointer}
#dsc-console.dsc-collapsed{grid-template-rows:1fr;width:74px}.dsc-collapsed .dsc-head{height:100%;padding:12px;display:flex;align-items:flex-start;justify-content:center}.dsc-collapsed .dsc-head>div,.dsc-collapsed .dsc-progress-row,.dsc-collapsed #dsc-metrics,.dsc-collapsed .dsc-main,.dsc-collapsed .dsc-foot{display:none!important}.dsc-collapsed .dsc-collapse{min-width:44px;width:44px;min-height:88px;writing-mode:vertical-rl}
.dsc-chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.dsc-chip{border:1px solid var(--dsc-line);background:#fff;border-radius:999px;padding:7px 11px;font-size:13px;color:#4f5f73}.dsc-chip.executing,.dsc-chip.running,.dsc-chip.approved{background:#eff6ff;border-color:#bfdbfe;color:#1d4ed8}.dsc-chip.awaiting_approval{background:#fff7df;border-color:#f2d38a;color:#8a5a00}.dsc-chip.blocked,.dsc-chip.failed{background:#fff1f2;border-color:#fecdd3;color:#be123c}
.dsc-progress-row{padding:14px 24px;border-bottom:1px solid var(--dsc-line);background:#f8fafc}.dsc-progress-copy{display:flex;justify-content:space-between;gap:12px;color:#526074;font-size:14px;margin-bottom:8px}.dsc-progress{height:9px;background:#e8eef6;border-radius:999px;overflow:hidden}.dsc-progress span{display:block;height:100%;width:0;background:linear-gradient(90deg,#2563eb,#10b981);transition:width .35s ease}
#dsc-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:14px 24px;border-bottom:1px solid var(--dsc-line);background:#fff}.dsc-metric{border:1px solid var(--dsc-line);border-radius:8px;background:#f8fafc;padding:13px;min-height:72px}.dsc-metric b{display:block;font-size:20px}.dsc-metric span{display:block;margin-top:6px;color:var(--dsc-muted);font-size:13px}
.dsc-main{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.95fr);min-height:0}.dsc-list,.dsc-detail{min-width:0;min-height:0;overflow:auto;padding:18px}.dsc-list{border-right:1px solid var(--dsc-line)}.dsc-section-title{font-size:16px;font-weight:850;margin:0 0 12px;display:flex;align-items:center;justify-content:space-between;gap:10px}.dsc-filter{min-height:40px;border:1px solid var(--dsc-line);border-radius:8px;background:#fff;padding:0 10px;color:#283448}
.dsc-task-row{width:100%;border:1px solid var(--dsc-line);background:#fff;border-radius:8px;padding:13px;margin-bottom:10px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;text-align:left;cursor:pointer;min-height:76px}.dsc-task-row[aria-selected=true]{border-color:#93c5fd;box-shadow:0 0 0 3px rgba(59,130,246,.15)}.dsc-task-name{display:block;font-weight:850;font-size:15px;line-height:1.35;word-break:break-word}.dsc-task-meta{display:block;color:var(--dsc-muted);font-size:13px;margin-top:4px;line-height:1.35}.dsc-status{align-self:start;border:1px solid var(--dsc-line);border-radius:999px;padding:4px 8px;color:#526074;font-size:12px;white-space:nowrap}
.dsc-detail-title{font-size:21px;font-weight:900;line-height:1.25;margin-bottom:12px}.dsc-detail-line{font-size:14px;line-height:1.55;color:#405068;margin:8px 0;word-break:break-word}.dsc-detail-section{border:1px solid var(--dsc-line);border-radius:8px;background:#fff;margin:10px 0;overflow:hidden}.dsc-detail-section summary{cursor:pointer;font-weight:850;padding:11px 12px}.dsc-detail-section div,.dsc-detail-section pre{white-space:pre-wrap;margin:0;padding:0 12px 12px;color:#475569;font:13px/1.55 ui-sans-serif,system-ui,sans-serif;overflow-wrap:anywhere}.dsc-empty{border:1px dashed var(--dsc-line);border-radius:8px;padding:16px;color:var(--dsc-muted);background:#fff}
.dsc-foot{border-top:1px solid var(--dsc-line);padding:11px 20px;display:flex;justify-content:space-between;gap:12px;color:#6b778b;font-size:12px;background:#fff}.dsc-foot a{color:#2563eb;text-decoration:none}
#dsc-offline{display:none;position:fixed;inset:0;z-index:2147483001;background:rgba(15,23,42,.72);color:#fff;align-items:center;justify-content:center;text-align:center;padding:24px}.dsc-offline #dsc-offline{display:flex}.dsc-offline-card{max-width:460px;border:1px solid rgba(255,255,255,.24);border-radius:8px;background:rgba(15,23,42,.94);padding:22px}
@keyframes dsc-work{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
@media (max-width:760px){
  html,body{overflow:auto;background:#f8fafc!important}
  #root,#dsc-war{display:none!important}
  #dsc-console{position:relative;inset:auto;width:100%;min-height:100dvh;border-left:0;box-shadow:none;display:block}
  .dsc-head{position:sticky;top:0;z-index:2;padding:16px;background:#fff}.dsc-title{font-size:20px}.dsc-collapse{display:none}
  .dsc-progress-row,#dsc-metrics,.dsc-list,.dsc-detail{padding-left:16px;padding-right:16px}
  #dsc-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}
  .dsc-main{display:block}.dsc-list{border-right:0;border-bottom:1px solid var(--dsc-line)}
  .dsc-detail{position:fixed;left:0;right:0;bottom:0;max-height:74dvh;background:#f8fafc;border-top:1px solid var(--dsc-line);box-shadow:0 -20px 44px rgba(15,23,42,.22);transform:translateY(calc(100% - 64px));transition:transform .24s ease;border-radius:14px 14px 0 0}
  .dsc-detail::before{content:"任务详情";display:block;font-weight:900;font-size:16px;margin-bottom:10px}.dsc-detail-open .dsc-detail{transform:translateY(0)}
  .dsc-foot{position:sticky;bottom:0}.dsc-chip{font-size:12px;padding:6px 9px}
}
</style>`;

  const markup = `<section id="dsc-war" aria-hidden="true">
  <div id="dsc-board" class="dsc-room-card"></div>
  <div id="dsc-ops">
    <div class="dsc-zone dsc-room-card zone-work"><div class="dsc-zone-title">工位区<span>执行中的角色</span></div><div class="dsc-zone-grid" data-zone="work"></div></div>
    <div class="dsc-zone dsc-room-card zone-dispatch"><div class="dsc-zone-title">派发区<span>等待分配</span></div><div class="dsc-zone-grid" data-zone="dispatch"></div></div>
    <div class="dsc-zone dsc-room-card zone-lounge"><div class="dsc-zone-title">休息区<span>完成 / 空闲</span></div><div class="dsc-zone-grid" data-zone="lounge"></div></div>
    <div class="dsc-zone dsc-room-card zone-review"><div class="dsc-zone-title">验收区<span>证据检查</span></div><div class="dsc-zone-grid" data-zone="review"></div></div>
    <div class="dsc-zone dsc-room-card zone-issue"><div class="dsc-zone-title">问题区<span>阻塞 / 失败</span></div><div class="dsc-zone-grid" data-zone="issue"></div></div>
  </div>
  <div id="dsc-feed"></div>
</section>
<section id="dsc-console" aria-label="DeepSeekCode 多 Agent 控制台">
  <header class="dsc-head"><div><div class="dsc-brand">DeepSeekCode Agents</div><div id="dsc-title" class="dsc-title">正在读取任务...</div><div id="dsc-chips" class="dsc-chips"></div></div><button id="dsc-collapse" class="dsc-collapse" type="button">收起</button></header>
  <div class="dsc-progress-row"><div class="dsc-progress-copy"><span id="dsc-progress-label">0/0 已完成</span><span id="dsc-next">等待进展</span></div><div class="dsc-progress"><span id="dsc-progress"></span></div></div>
  <div id="dsc-metrics"></div>
  <main id="dsc-main" class="dsc-main"><section class="dsc-list"><h2 class="dsc-section-title">任务清单 <select id="dsc-filter" class="dsc-filter"><option value="unfinished">未完成</option><option value="all">全部</option><option value="running">执行中</option><option value="needs_review">待验收</option><option value="blocked">失败/阻塞</option><option value="succeeded">已完成</option></select></h2><div id="dsc-task-list"></div></section><aside id="dsc-detail" class="dsc-detail"></aside></main>
  <footer class="dsc-foot"><span id="dsc-updated">等待 snapshot</span><a id="dsc-trace" href="#" target="_blank" rel="noreferrer">trace</a></footer>
</section>
<div id="dsc-offline"><div class="dsc-offline-card"><h2>本机 DeepSeekCode 已断开</h2><p id="dsc-offline-text">页面保留最后一次状态。重新启动 TUI 后刷新或重新打开面板。</p></div></div>`;

  const script = `<script>
(() => {
  const panel = window.DEEPSEEKCODE_PIXEL_PANEL; if (!panel) return;
  const token = panel.token || new URLSearchParams(location.search).get("token") || "";
  const $ = (id) => document.getElementById(id);
  const title=$("dsc-title"),chips=$("dsc-chips"),progressLabel=$("dsc-progress-label"),progress=$("dsc-progress"),next=$("dsc-next"),metrics=$("dsc-metrics"),list=$("dsc-task-list"),detail=$("dsc-detail"),filter=$("dsc-filter"),board=$("dsc-board"),feed=$("dsc-feed"),updated=$("dsc-updated"),trace=$("dsc-trace"),main=$("dsc-main"),consoleEl=$("dsc-console");
  let selected="", pollTimer=0, disconnected=false;
  function esc(v){return String(v == null ? "" : v).replace(/[&<>"]/g, ch => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;" }[ch]));}
  function compact(v,n=90){const s=String(v == null ? "" : v).replace(/\\s+/g," ").trim();return s.length>n?s.slice(0,n-1)+"...":s;}
  function api(path){return panel.api + path + (path.includes("?") ? "&" : "?") + "token=" + encodeURIComponent(token);}
  function hasChinese(v){return /[\\u4e00-\\u9fff]/.test(String(v||""));}
  function roleLabel(v){const raw=String(v||""); if(hasChinese(raw))return raw; const s=raw.toLowerCase(); if(s==="planner")return "规划负责人"; if(s==="acceptancereviewer")return "验收负责人"; if(/review|accept|qa|test|verify/.test(s))return "验证工程师"; if(/front|ui|web|visual/.test(s))return "界面交互工程师"; if(/back|api|server|data|db/.test(s))return "后端数据工程师"; if(/motion|gsap|animation|game/.test(s))return "动效玩法工程师"; if(/doc|pdf|office|report/.test(s))return "文档交付工程师"; if(/implementation|builder|worker/.test(s))return "任务执行工程师"; return raw || "未分配";}
  function statusText(v){return ({queued:"排队中",running:"执行中",needs_review:"待验收",succeeded:"已完成",failed:"失败",blocked:"阻塞",skipped:"已跳过",paused:"等待中",cancelled:"已取消",defined:"待命",idle:"休息中"}[v]||v||"未知");}
  function phaseText(v){return ({planning:"规划中",awaiting_approval:"等待确认",executing:"执行中",reviewing:"验收中",completed:"已完成",blocked:"已阻塞",cancelled:"已取消"}[v]||v||"初始化");}
  function approvalText(v){return ({pending:"待确认",approved:"已批准",revision_requested:"待修改",regenerating:"重生成",cancelled:"已取消",not_required:"无需确认"}[v]||v||"");}
  function chip(v,cls){return v?'<span class="dsc-chip '+esc(cls||"")+'">'+esc(v)+'</span>':"";}
  function visible(task){const v=filter.value||"unfinished"; if(v==="all")return true; if(v==="unfinished")return !["succeeded","skipped"].includes(task.status); if(v==="blocked")return ["blocked","failed"].includes(task.status); return task.status===v;}
  function zoneFor(role,snapshot){const model=snapshot.layoutModel&&snapshot.layoutModel.roleLocations?snapshot.layoutModel.roleLocations[role.role]:""; if(model==="workbench")return "work"; if(model==="dispatch")return "dispatch"; if(model==="review")return "review"; if(model==="blocked")return "issue"; if(model==="lounge")return "lounge"; if(role.blockedBy||role.status==="failed"||role.status==="blocked")return "issue"; if(role.status==="running")return "work"; if(/验收|验证|review|accept|test|verify/i.test(roleLabel(role.role)))return "review"; if(role.status==="queued"||role.status==="paused")return "dispatch"; return "lounge";}
  function renderBoard(snapshot){const tasks=snapshot.subtaskGraph||[], ready=new Set((snapshot.readyQueue||[]).map(x=>x.id)), c=snapshot.completionSummary||{total:tasks.length,succeeded:0,skipped:0,percent:0}; const focus=tasks.filter(t=>!["succeeded","skipped"].includes(t.status)).sort((a,b)=>(ready.has(b.id)?1:0)-(ready.has(a.id)?1:0)).slice(0,9); board.innerHTML='<div class="dsc-board-head">会议室任务黑板<span>'+esc((c.succeeded||0)+(c.skipped||0))+'/'+esc(c.total||0)+'</span></div><div class="dsc-board-progress"><span style="width:'+Math.max(0,Math.min(100,c.percent||0))+'%"></span></div><div class="dsc-board-grid">'+(focus.length?focus.map(t=>'<div class="dsc-board-item"><span class="dsc-dot '+esc(t.status)+'"></span><span><span class="dsc-board-name">'+esc(compact(t.title,38))+'</span><span class="dsc-board-meta">'+esc(roleLabel(t.assigneeRole))+' - '+esc(ready.has(t.id)?"可执行":((t.dependencies||[]).length?("依赖 "+t.dependencies.length):"无依赖"))+'</span></span><span class="dsc-board-status">'+esc(statusText(t.status))+'</span></div>').join(""):'<div class="dsc-board-item"><span class="dsc-dot succeeded"></span><span><span class="dsc-board-name">暂无未完成任务</span><span class="dsc-board-meta">等待验收或新任务</span></span><span class="dsc-board-status">同步中</span></div>')+'</div>';}
  function roleCard(r,t){return '<div class="dsc-role '+esc(r.status||"")+'"><span class="dsc-role-name">'+esc(roleLabel(r.role))+'</span><span class="dsc-role-line">'+esc(statusText(r.status))+'</span><span class="dsc-role-task">'+esc(compact(t||r.currentTask||"等待任务",54))+'</span></div>';}
  function renderStage(snapshot){const tasks=snapshot.subtaskGraph||[], roles=snapshot.roles||[], groups={work:[],dispatch:[],lounge:[],review:[],issue:[]}; roles.forEach(r=>{const task=r.currentTask||tasks.find(t=>t.assigneeRole===r.role&&!["succeeded","skipped"].includes(t.status))?.title||""; groups[zoneFor(r,snapshot)].push(roleCard(r,task));}); for(const zone of Object.keys(groups)){const el=document.querySelector('[data-zone="'+zone+'"]'); if(!el)continue; const base=zone==="work"?"dsc-desk":"dsc-seat"; const cards=groups[zone]; el.innerHTML=Array.from({length:Math.max(cards.length,zone==="work"?4:2)},(_,i)=>'<div class="'+base+'">'+(cards[i]||"")+'</div>').join("");}}
  function renderFeed(snapshot){const events=(snapshot.timeline||[]).slice(-3).reverse(), evidence=(snapshot.evidence||[]).slice(-3).reverse(), processes=(snapshot.processes||[]).filter(p=>p.status==="running").slice(0,3), cache=snapshot.cacheSummary||{}; feed.innerHTML='<div class="dsc-feed-card dsc-room-card"><b>最新事件</b>'+(events.length?events.map(e=>'<span>'+esc(compact([roleLabel(e.role),e.tool,e.message||e.kind].filter(Boolean).join(" - "),70))+'</span>').join(""):'<span>等待事件</span>')+'</div><div class="dsc-feed-card dsc-room-card"><b>产物 / Evidence</b>'+(evidence.length?evidence.map(e=>'<span><span class="dsc-pill">'+esc(e.kind)+'</span>'+esc(compact(e.path||e.url||e.summary,64))+'</span>').join(""):'<span>暂无 evidence</span>')+'</div><div class="dsc-feed-card dsc-room-card"><b>运行 / 缓存</b>'+(processes.length?processes.map(p=>'<span>'+esc(compact((p.url||p.command)+" - pid "+p.pid,70))+'</span>').join(""):'<span>暂无运行进程</span>')+(cache.cacheHitRate==null?'':'<span>缓存命中 '+esc(Math.round(cache.cacheHitRate*100))+'%</span>')+'</div>';}
  function renderDetail(snapshot,task){if(!task){detail.innerHTML='<div class="dsc-empty">选择任务查看证据、验收标准、角色 skill 和工具摘要。</div>';return;} const role=(snapshot.roles||[]).find(r=>r.role===task.assigneeRole)||{}, skill=(snapshot.generatedSkills||[]).find(s=>s.id===role.generatedSkillId||s.role===role.role)||{}, evid=(snapshot.evidenceBySubtask&&snapshot.evidenceBySubtask[task.id])||[], issue=task.blockedBy||role.blockedBy||"", raw=[...(role.toolResultSummary||[]),role.lastMessage,role.checkpoint].filter(Boolean).join("\\n"); detail.innerHTML='<div class="dsc-detail-title">'+esc(task.title)+'</div><div class="dsc-detail-line"><b>负责人</b> '+esc(roleLabel(task.assigneeRole))+' - '+esc(statusText(task.status))+'</div><div class="dsc-detail-line"><b>依赖</b> '+esc((task.dependencies||[]).join(", ")||"无")+'</div><div class="dsc-detail-line"><b>最近事件</b> '+esc(task.lastEvent||role.lastTool||"暂无")+'</div><details class="dsc-detail-section" open><summary>验收标准与 evidence</summary><div><b>验收：</b>'+esc((task.acceptanceCriteria||[]).join(" | ")||"暂无")+'\\n\\n<b>任务证据：</b>'+esc(evid.length?evid.map(e=>e.kind+":"+(e.path||e.url||e.summary)).join("\\n"):(task.evidence||[]).join(" | ")||"暂无")+'</div></details><details class="dsc-detail-section"><summary>角色专属 skill</summary><div>'+esc(skill.summary||role.generatedSkillSummary||"暂无 role-local skill 摘要")+'\\n\\n'+esc(skill.prompt||"")+'</div></details><details class="dsc-detail-section"><summary>职责与上下文范围</summary><div>'+esc(role.responsibility||"暂无")+'\\n\\n'+esc(role.contextScope||"暂无")+'</div></details>'+(issue?'<details class="dsc-detail-section" open><summary>错误/阻塞摘要</summary><div>'+esc(issue)+'</div></details>':'')+'<details class="dsc-detail-section"><summary>Checkpoint / 工具摘要 / 原始输出</summary><pre>'+esc(raw||"暂无。完整日志保留在本地 trace。")+'</pre></details>';}
  function render(snapshot){const tasks=snapshot.subtaskGraph||[], c=snapshot.completionSummary||{total:tasks.length,succeeded:0,skipped:0,running:0,needsReview:0,blocked:0,failed:0,percent:0}, mobile=snapshot.mobileSummary||{}; title.textContent=snapshot.overview?.objective||mobile.objective||"DeepSeekCode 多 Agent"; chips.innerHTML=chip(phaseText(snapshot.phase||snapshot.overview?.phase),snapshot.phase)+chip(approvalText(snapshot.approvalState?.status),snapshot.approvalState?.status)+chip(mobile.overallProgress||""); progressLabel.textContent=mobile.overallProgress?mobile.overallProgress+" 已完成":((c.succeeded||0)+(c.skipped||0))+"/"+(c.total||0)+" 已完成"; progress.style.width=Math.max(0,Math.min(100,c.percent||0))+"%"; next.textContent=mobile.nextStep||"等待下一步"; metrics.innerHTML=[["未完成",Math.max(0,(c.total||0)-(c.succeeded||0)-(c.skipped||0))],["执行中",c.running||0],["待验收",c.needsReview||0],["失败/阻塞",(c.blocked||0)+(c.failed||0)]].map(([l,v])=>'<div class="dsc-metric"><b>'+esc(v)+'</b><span>'+esc(l)+'</span></div>').join(""); const shown=tasks.filter(visible); list.innerHTML=shown.length?shown.map(t=>'<button class="dsc-task-row" type="button" data-id="'+esc(t.id)+'" aria-selected="'+(t.id===selected)+'"><span class="dsc-dot '+esc(t.status)+'"></span><span><span class="dsc-task-name">'+esc(t.title)+'</span><span class="dsc-task-meta">'+esc(roleLabel(t.assigneeRole))+' - '+esc((t.dependencies||[]).length?("依赖 "+t.dependencies.join(", ")):"无依赖")+'</span></span><span class="dsc-status">'+esc(statusText(t.status))+'</span></button>').join(""):'<div class="dsc-empty">当前没有任务数据。面板会自动追踪本项目 active workflow。</div>'; list.querySelectorAll("[data-id]").forEach(n=>n.addEventListener("click",()=>{selected=n.dataset.id||""; main.classList.add("dsc-detail-open"); renderDetail(snapshot,tasks.find(t=>t.id===selected)); list.querySelectorAll("[data-id]").forEach(x=>x.setAttribute("aria-selected",String(x.dataset.id===selected)));})); if(!selected&&tasks.length)selected=tasks[0].id; renderDetail(snapshot,tasks.find(t=>t.id===selected)); renderBoard(snapshot); renderStage(snapshot); renderFeed(snapshot); updated.textContent=snapshot.generatedAtMs?"更新于 "+new Date(snapshot.generatedAtMs).toLocaleTimeString():"等待 snapshot"; trace.href=api("/trace.jsonl");}
  function offline(message){if(disconnected)return; disconnected=true; document.body.classList.add("dsc-offline"); $("dsc-offline-text").textContent=message||"本机 DeepSeekCode 已断开，页面保留最后一次状态。"; if(pollTimer)clearInterval(pollTimer);}
  async function tick(){if(disconnected)return; try{const res=await fetch(api("/snapshot"),{cache:"no-store"}); if(!res.ok)throw new Error("HTTP "+res.status); render(await res.json());}catch(e){offline("无法连接本机 DeepSeekCode："+(e&&e.message?e.message:e));}}
  function connect(){try{const u=new URL("/ws",location.href); u.protocol=u.protocol==="https:"?"wss:":"ws:"; u.searchParams.set("runId",panel.runId); u.searchParams.set("token",token); const ws=new WebSocket(u.toString()); ws.addEventListener("message",e=>{try{const m=JSON.parse(e.data); if(m.type==="serverShutdown")offline(m.message||"本机 DeepSeekCode 已关闭。");}catch{}}); ws.addEventListener("close",()=>offline("本机 DeepSeekCode 连接已断开。")); ws.addEventListener("error",()=>offline("本机 DeepSeekCode 连接异常。"));}catch{}}
  $("dsc-collapse").addEventListener("click",()=>{const collapsed=!consoleEl.classList.contains("dsc-collapsed"); consoleEl.classList.toggle("dsc-collapsed",collapsed); document.documentElement.style.setProperty("--dsc-console-w",collapsed?"74px":"clamp(600px,42vw,820px)"); $("dsc-collapse").textContent=collapsed?"展开":"收起";});
  filter.addEventListener("change",()=>tick());
  document.addEventListener("click",e=>{if(e.target===detail)main.classList.remove("dsc-detail-open");});
  connect(); tick(); pollTimer=setInterval(tick,1500);
})();
</script>`;
  return { style, markup, script };
}
