export function buildAgentDashboardOverlay(): { style: string; markup: string; script: string } {
  const style = `<style>
:root{--dsc-console-w:clamp(520px,40vw,760px);--dsc-ink:#162033;--dsc-muted:#607086;--dsc-line:#d7e0ec;--dsc-blue:#2563eb;--dsc-green:#15845b;--dsc-amber:#ad7400;--dsc-red:#c43b3b;--dsc-bg:#101321}
html,body,#root{width:100%;height:100%;margin:0;overflow:hidden;background:var(--dsc-bg)!important}
body{font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0}
#root{position:fixed!important;inset:0 var(--dsc-console-w) 0 0!important;width:auto!important;height:auto!important;overflow:hidden!important;background:#151625!important}
#root canvas,#root img{image-rendering:pixelated}
#root canvas.block{width:100%!important;height:100%!important;object-fit:cover;transform:scale(1.16);transform-origin:center center}
#root [title*="Zoom"],#root .absolute.top-8.left-8.z-10,#root .absolute.bottom-10.left-10.z-20,#root .absolute.bottom-8.right-28.z-20,#root [style*="z-index: 41"][style*="pointer-events: none"]{display:none!important}
.dsc-native-hidden{display:none!important}
#dsc-war{position:fixed;inset:0 var(--dsc-console-w) 0 0;z-index:2147482997;pointer-events:none;color:#eef7ff;display:grid;grid-template-rows:minmax(150px,22vh) minmax(0,1fr) minmax(110px,16vh);gap:14px;padding:18px;background:linear-gradient(90deg,rgba(7,10,20,.2),rgba(7,10,20,.34))}
#dsc-war *{box-sizing:border-box}
#dsc-board{pointer-events:auto;align-self:stretch;border:2px solid #8a6836;border-radius:8px;background:linear-gradient(180deg,#17291d,#0d1711);box-shadow:0 16px 38px rgba(0,0,0,.38),inset 0 0 0 1px rgba(255,255,255,.06);padding:14px 16px;overflow:hidden}
.dsc-board-head{display:flex;justify-content:space-between;gap:12px;align-items:center;font-weight:850;font-size:18px}
.dsc-board-head span{font-size:12px;color:#cce8c1}
.dsc-board-progress{height:8px;background:rgba(207,239,198,.16);border-radius:999px;margin:10px 0 8px;overflow:hidden}
.dsc-board-progress span{display:block;height:100%;background:linear-gradient(90deg,#77dd9c,#72d6f7);border-radius:999px;transition:width .35s ease}
.dsc-board-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 14px}
.dsc-board-item{min-width:0;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:8px;align-items:center;border-bottom:1px solid rgba(194,235,188,.16);padding:5px 0}
.dsc-board-dot,.dsc-dot{width:10px;height:10px;border-radius:99px;background:#8a96a8;box-shadow:0 0 0 4px rgba(255,255,255,.05)}
.dsc-board-dot.running,.dsc-dot.running{background:#60a5fa;box-shadow:0 0 0 4px rgba(96,165,250,.18)}
.dsc-board-dot.succeeded,.dsc-dot.succeeded{background:#34d399}.dsc-board-dot.needs_review,.dsc-dot.needs_review{background:#f6bd60}.dsc-board-dot.blocked,.dsc-board-dot.failed,.dsc-dot.blocked,.dsc-dot.failed{background:#fb7185}
.dsc-board-name{display:block;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:820;color:#f5fff1}
.dsc-board-meta{display:block;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;color:#b7c8bd;margin-top:2px}
.dsc-board-status{font-size:12px;color:#dff7d2;white-space:nowrap}
#dsc-map-overlay{position:relative;pointer-events:none}
.dsc-zone{position:absolute;border:1px solid rgba(226,238,255,.34);background:rgba(12,18,32,.28);border-radius:8px;color:#dbeafe;font-size:13px;font-weight:750;padding:6px 8px}
.zone-work{left:7%;top:12%;width:42%;height:52%}.zone-dispatch{left:52%;top:14%;width:18%;height:36%}.zone-lounge{right:6%;top:10%;width:22%;height:40%}.zone-evidence{left:7%;bottom:8%;right:6%;height:22%}
#dsc-role-layer{position:absolute;inset:0}.dsc-role-chip{position:absolute;min-width:150px;max-width:220px;transform:translate(-50%,-50%);border:1px solid rgba(207,225,252,.45);background:rgba(18,27,43,.92);border-radius:8px;padding:8px 10px;box-shadow:0 12px 28px rgba(0,0,0,.34);backdrop-filter:blur(8px);pointer-events:auto;transition:left .42s ease,top .42s ease,transform .22s ease}
.dsc-role-chip.running{border-color:#60a5fa;box-shadow:0 0 0 1px rgba(96,165,250,.28),0 14px 32px rgba(0,0,0,.38);animation:dsc-pulse 1.4s ease-in-out infinite}
.dsc-role-chip.failed,.dsc-role-chip.blocked{border-color:#fb7185}.dsc-role-name{display:block;color:#eff6ff;font-size:14px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dsc-role-status{display:block;color:#bfdbfe;font-size:12px;margin-top:2px}.dsc-role-task{display:block;color:#d9e6f5;font-size:12px;margin-top:4px;line-height:1.35;overflow:hidden;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}
#dsc-flow{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.dsc-flow-line{stroke:#67e8f9;stroke-width:1.6;stroke-dasharray:6 7;opacity:.55;animation:dsc-dash 1.6s linear infinite}
#dsc-feed{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.dsc-feed-card{pointer-events:auto;border:1px solid rgba(218,231,250,.28);border-radius:8px;background:rgba(11,17,30,.82);padding:12px;overflow:hidden}.dsc-feed-card b{display:block;font-size:13px;margin-bottom:7px;color:#f8fbff}.dsc-feed-card span{display:block;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#c8d6e8;font-size:12px;line-height:1.55}.dsc-feed-pill{display:inline-block!important;width:auto;border:1px solid rgba(103,232,249,.36);border-radius:999px;padding:1px 6px;margin-right:5px;color:#a5f3fc!important}
#dsc-console{position:fixed;right:0;top:0;bottom:0;width:var(--dsc-console-w);z-index:2147482999;background:#f8fafc;color:var(--dsc-ink);border-left:1px solid var(--dsc-line);display:grid;grid-template-rows:auto auto auto minmax(0,1fr) auto;box-shadow:-18px 0 48px rgba(6,14,30,.2)}
#dsc-console *{box-sizing:border-box;letter-spacing:0}.dsc-head{padding:22px 24px 16px;border-bottom:1px solid var(--dsc-line);display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;align-items:start;background:#fff}.dsc-brand{font-size:11px;color:#4f46e5;font-weight:850;text-transform:uppercase}.dsc-title{margin-top:8px;font-size:24px;line-height:1.18;font-weight:900;word-break:break-word}.dsc-collapse{min-width:52px;min-height:44px;border:1px solid var(--dsc-line);border-radius:8px;background:#fff;color:var(--dsc-ink);font-weight:750;cursor:pointer}
#dsc-console.dsc-collapsed{grid-template-rows:1fr;width:72px}.dsc-collapsed .dsc-head{height:100%;padding:12px;display:flex;align-items:flex-start;justify-content:center}.dsc-collapsed .dsc-head>div,.dsc-collapsed .dsc-progress-row,.dsc-collapsed #dsc-metrics,.dsc-collapsed .dsc-main,.dsc-collapsed .dsc-foot{display:none!important}.dsc-collapsed .dsc-collapse{min-width:44px;width:44px;min-height:88px;writing-mode:vertical-rl}
.dsc-chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.dsc-chip{border:1px solid var(--dsc-line);background:#fff;border-radius:999px;padding:7px 11px;font-size:13px;color:#4f5f73}.dsc-chip.executing,.dsc-chip.running,.dsc-chip.approved{background:#eff6ff;border-color:#bfdbfe;color:#1d4ed8}.dsc-chip.blocked,.dsc-chip.failed{background:#fff1f2;border-color:#fecdd3;color:#be123c}
.dsc-progress-row{padding:14px 24px;border-bottom:1px solid var(--dsc-line);background:#f8fafc}.dsc-progress-copy{display:flex;justify-content:space-between;gap:12px;color:#526074;font-size:14px;margin-bottom:8px}.dsc-progress{height:9px;background:#e8eef6;border-radius:999px;overflow:hidden}.dsc-progress span{display:block;height:100%;width:0;background:linear-gradient(90deg,#2563eb,#10b981);transition:width .35s ease}
#dsc-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:14px 24px;border-bottom:1px solid var(--dsc-line);background:#fff}.dsc-metric{border:1px solid var(--dsc-line);border-radius:8px;background:#f8fafc;padding:13px;min-height:72px}.dsc-metric b{display:block;font-size:20px}.dsc-metric span{display:block;margin-top:6px;color:var(--dsc-muted);font-size:13px}
.dsc-main{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,.95fr);min-height:0}.dsc-list,.dsc-detail{min-width:0;min-height:0;overflow:auto;padding:18px 18px 22px}.dsc-list{border-right:1px solid var(--dsc-line)}.dsc-section-title{font-size:16px;font-weight:850;margin:0 0 12px;display:flex;align-items:center;justify-content:space-between;gap:10px}.dsc-filter{min-height:40px;border:1px solid var(--dsc-line);border-radius:8px;background:#fff;padding:0 10px;color:#283448}
.dsc-task-row{width:100%;border:1px solid var(--dsc-line);background:#fff;border-radius:8px;padding:13px;margin-bottom:10px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;text-align:left;cursor:pointer;min-height:76px}.dsc-task-row[aria-selected=true]{border-color:#93c5fd;box-shadow:0 0 0 3px rgba(59,130,246,.15)}.dsc-task-name{display:block;font-weight:850;font-size:15px;line-height:1.35;word-break:break-word}.dsc-task-meta{display:block;color:var(--dsc-muted);font-size:13px;margin-top:4px;line-height:1.35}.dsc-status{align-self:start;border:1px solid var(--dsc-line);border-radius:999px;padding:4px 8px;color:#526074;font-size:12px;white-space:nowrap}
.dsc-detail-title{font-size:21px;font-weight:900;line-height:1.25;margin-bottom:12px}.dsc-detail-line{font-size:14px;line-height:1.55;color:#405068;margin:8px 0;word-break:break-word}.dsc-detail-section{border:1px solid var(--dsc-line);border-radius:8px;background:#fff;margin:10px 0;overflow:hidden}.dsc-detail-section summary{cursor:pointer;font-weight:850;padding:11px 12px}.dsc-detail-section div,.dsc-detail-section pre{white-space:pre-wrap;margin:0;padding:0 12px 12px;color:#475569;font:13px/1.55 ui-sans-serif,system-ui,sans-serif;overflow-wrap:anywhere}.dsc-empty{border:1px dashed var(--dsc-line);border-radius:8px;padding:16px;color:var(--dsc-muted);background:#fff}
.dsc-foot{border-top:1px solid var(--dsc-line);padding:11px 20px;display:flex;justify-content:space-between;gap:12px;color:#6b778b;font-size:12px;background:#fff}.dsc-foot a{color:#2563eb;text-decoration:none}.dsc-offline #dsc-offline{display:flex}#dsc-offline{display:none;position:fixed;inset:0;z-index:2147483001;background:rgba(15,23,42,.72);color:#fff;align-items:center;justify-content:center;text-align:center;padding:24px}.dsc-offline-card{max-width:460px;border:1px solid rgba(255,255,255,.24);border-radius:8px;background:rgba(15,23,42,.92);padding:22px}
@keyframes dsc-pulse{0%,100%{transform:translate(-50%,-50%) translateY(0)}50%{transform:translate(-50%,-50%) translateY(-4px)}}@keyframes dsc-dash{to{stroke-dashoffset:-26}}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
@media (max-width:760px){html,body{overflow:auto;background:#f8fafc!important}#root,#dsc-war{display:none!important}#dsc-console{position:relative;inset:auto;width:100%;min-height:100dvh;border-left:0;box-shadow:none;display:block}.dsc-head{position:sticky;top:0;z-index:2;padding:16px 16px 12px}.dsc-title{font-size:20px}.dsc-collapse{display:none}.dsc-progress-row,#dsc-metrics,.dsc-list,.dsc-detail{padding-left:16px;padding-right:16px}#dsc-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.dsc-main{display:block}.dsc-list{border-right:0;border-bottom:1px solid var(--dsc-line)}.dsc-detail{position:fixed;left:0;right:0;bottom:0;max-height:74dvh;background:#f8fafc;border-top:1px solid var(--dsc-line);box-shadow:0 -20px 44px rgba(15,23,42,.22);transform:translateY(calc(100% - 64px));transition:transform .24s ease;border-radius:14px 14px 0 0}.dsc-detail::before{content:"任务详情";display:block;font-weight:900;font-size:16px;margin-bottom:10px}.dsc-detail-open .dsc-detail{transform:translateY(0)}.dsc-task-row{min-height:72px}.dsc-detail-title{font-size:18px}.dsc-foot{position:sticky;bottom:0}.dsc-chip{font-size:12px;padding:6px 9px}}
</style>`;
  const markup = `<section id="dsc-war" aria-hidden="true">
  <div id="dsc-board"></div>
  <div id="dsc-map-overlay">
    <svg id="dsc-flow" viewBox="0 0 100 100" preserveAspectRatio="none"></svg>
    <div class="dsc-zone zone-work">工位区</div>
    <div class="dsc-zone zone-dispatch">派发区</div>
    <div class="dsc-zone zone-lounge">休息区</div>
    <div class="dsc-zone zone-evidence">产物角</div>
    <div id="dsc-role-layer"></div>
  </div>
  <div id="dsc-feed"></div>
</section>
<section id="dsc-console" aria-label="DeepSeekCode 多 Agent 控制台">
  <header class="dsc-head"><div><div class="dsc-brand">DeepSeekCode Agents</div><div id="dsc-title" class="dsc-title">正在读取任务...</div><div id="dsc-chips" class="dsc-chips"></div></div><button id="dsc-collapse" class="dsc-collapse" type="button">收起</button></header>
  <div class="dsc-progress-row"><div class="dsc-progress-copy"><span id="dsc-progress-label">0/0 已完成</span><span id="dsc-next">等待进展</span></div><div class="dsc-progress"><span id="dsc-progress"></span></div></div>
  <div id="dsc-metrics"></div>
  <main id="dsc-main" class="dsc-main"><section class="dsc-list"><h2 class="dsc-section-title">任务清单 <select id="dsc-filter" class="dsc-filter"><option value="unfinished">未完成</option><option value="all">全部</option><option value="running">执行中</option><option value="needs_review">待验收</option><option value="blocked">失败/阻塞</option><option value="succeeded">已完成</option></select></h2><div id="dsc-task-list"></div></section><aside id="dsc-detail" class="dsc-detail"></aside></main>
  <footer class="dsc-foot"><span id="dsc-updated">等待 snapshot</span><a id="dsc-trace" href="#" target="_blank" rel="noreferrer">trace</a></footer>
</section>
<div id="dsc-offline"><div class="dsc-offline-card"><h2>本机 DeepSeekCode 已断开</h2><p id="dsc-offline-text">页面保留最后一次状态。重新启动 TUI 后刷新或重新打开面板。</p></div></div>`;
  const script = `<script>
(() => {
  const panel = window.DEEPSEEKCODE_PIXEL_PANEL; if (!panel) return;
  const token = panel.token || new URLSearchParams(location.search).get("token") || "";
  const title = document.getElementById("dsc-title"), chips = document.getElementById("dsc-chips"), progressLabel = document.getElementById("dsc-progress-label"), progress = document.getElementById("dsc-progress"), next = document.getElementById("dsc-next"), metrics = document.getElementById("dsc-metrics"), list = document.getElementById("dsc-task-list"), detail = document.getElementById("dsc-detail"), filter = document.getElementById("dsc-filter"), board = document.getElementById("dsc-board"), roleLayer = document.getElementById("dsc-role-layer"), feed = document.getElementById("dsc-feed"), flow = document.getElementById("dsc-flow"), updated = document.getElementById("dsc-updated"), trace = document.getElementById("dsc-trace"), main = document.getElementById("dsc-main");
  let selected = "", pollTimer = 0, disconnected = false;
  const workSlots=[[21,26],[34,28],[24,48],[39,50],[18,66]], dispatchSlots=[[61,32],[61,52],[55,68]], loungeSlots=[[80,28],[88,42],[78,58],[88,70]], blockedSlots=[[49,18],[70,18]], reviewSlots=[[60,72],[72,72]];
  function esc(v){return String(v == null ? "" : v).replace(/[&<>"]/g, ch => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;" }[ch]));}
  function compact(v,n){const s=String(v == null ? "" : v).replace(/\\s+/g," ").trim();const limit=n||90;return s.length>limit?s.slice(0,limit-1)+"...":s;}
  function api(path){return panel.api + path + (path.includes("?") ? "&" : "?") + "token=" + encodeURIComponent(token);}
  function isChinese(v){return /[\\u4e00-\\u9fff]/.test(String(v||""));}
  function roleLabel(v){const raw=String(v||""); if(isChinese(raw)) return raw; const known={Planner:"规划负责人",AcceptanceReviewer:"验收负责人",ImplementationSpecialist:"实现工程师",RuntimeImplementationSpecialist:"运行修复工程师",Builder:"实现工程师",Worker:"执行工程师",Frontend:"前端工程师",Backend:"后端工程师",Tester:"验证工程师"}; if(known[raw]) return known[raw]; const s=raw.toLowerCase(); if(/plan/.test(s))return "规划负责人"; if(/review|accept|qa|test|verify/.test(s))return "验收负责人"; if(/front|ui|web|visual/.test(s))return "前端体验工程师"; if(/back|api|server|data|db/.test(s))return "后端数据工程师"; if(/motion|gsap|animation|game/.test(s))return "动效交互工程师"; if(/doc|pdf|office|report/.test(s))return "文档交付工程师"; return raw || "未分配";}
  function statusText(v){return ({queued:"排队中",running:"执行中",needs_review:"待验收",succeeded:"已完成",failed:"失败",blocked:"阻塞",skipped:"已跳过",paused:"等待中",cancelled:"已取消",defined:"待命",idle:"休息中"}[v]||v||"未知");}
  function phaseText(v){return ({planning:"规划中",awaiting_approval:"等待确认",executing:"执行中",reviewing:"验收中",completed:"已完成",blocked:"已阻塞",cancelled:"已取消"}[v]||v||"初始化");}
  function approvalText(v){return ({pending:"待确认",approved:"已批准",revision_requested:"待修改",regenerating:"重生成",cancelled:"已取消",not_required:"无需确认"}[v]||v||"");}
  function chip(v,cls){return v?'<span class="dsc-chip '+esc(cls||"")+'">'+esc(v)+'</span>':"";}
  function zoneFor(role,snapshot){const model=snapshot.layoutModel&&snapshot.layoutModel.roleLocations?snapshot.layoutModel.roleLocations[role.role]:""; if(model==="workbench")return "work"; if(model==="dispatch")return "dispatch"; if(model==="review")return "review"; if(model==="blocked")return "blocked"; if(model==="lounge")return "lounge"; if(role.blockedBy||role.status==="failed")return "blocked"; if(role.status==="running")return "work"; if(/验收|review|accept|test|verify/i.test(role.role))return "review"; if(role.status==="queued"||role.status==="paused")return "dispatch"; return "lounge";}
  function point(zone,i){const slots=zone==="work"?workSlots:zone==="dispatch"?dispatchSlots:zone==="review"?reviewSlots:zone==="blocked"?blockedSlots:loungeSlots; return slots[i%slots.length];}
  function visible(task){const v=filter.value||"unfinished"; if(v==="all")return true; if(v==="unfinished")return !["succeeded","skipped"].includes(task.status); if(v==="blocked")return ["blocked","failed"].includes(task.status); return task.status===v;}
  function renderBoard(snapshot){const tasks=snapshot.subtaskGraph||[], ready=new Set((snapshot.readyQueue||[]).map(x=>x.id)), c=snapshot.completionSummary||{total:tasks.length,succeeded:0,skipped:0,percent:0}; const focus=tasks.filter(t=>!["succeeded","skipped"].includes(t.status)).sort((a,b)=>(ready.has(b.id)?1:0)-(ready.has(a.id)?1:0)).slice(0,8); board.innerHTML='<div class="dsc-board-head">会议室任务黑板 <span>'+esc((c.succeeded||0)+(c.skipped||0))+'/'+esc(c.total||0)+'</span></div><div class="dsc-board-progress"><span style="width:'+Math.max(0,Math.min(100,c.percent||0))+'%"></span></div><div class="dsc-board-grid">'+(focus.length?focus.map(t=>'<div class="dsc-board-item"><span class="dsc-board-dot '+esc(t.status)+'"></span><span><span class="dsc-board-name">'+esc(compact(t.title,46))+'</span><span class="dsc-board-meta">'+esc(roleLabel(t.assigneeRole))+' · '+esc(ready.has(t.id)?"可执行":((t.dependencies||[]).length?("依赖 "+t.dependencies.length):"无依赖"))+'</span></span><span class="dsc-board-status">'+esc(statusText(t.status))+'</span></div>').join(""):'<div class="dsc-board-item"><span class="dsc-board-dot succeeded"></span><span><span class="dsc-board-name">暂无未完成任务</span><span class="dsc-board-meta">等待验收或新任务</span></span><span class="dsc-board-status">同步中</span></div>')+'</div>';}
  function renderStage(snapshot){const roles=snapshot.roles||[], tasks=snapshot.subtaskGraph||[]; roleLayer.innerHTML=roles.map((r,i)=>{const z=zoneFor(r,snapshot), p=point(z,i), task=r.currentTask||tasks.find(t=>t.assigneeRole===r.role&&!["succeeded","skipped"].includes(t.status))?.title||(z==="lounge"?"休息区待命":"等待派发"); return '<div class="dsc-role-chip '+esc(r.status||"")+'" style="left:'+p[0]+'%;top:'+p[1]+'%"><span class="dsc-role-name">'+esc(roleLabel(r.role))+'</span><span class="dsc-role-status">'+esc(statusText(r.status))+' · '+esc(z==="work"?"工位区":z==="dispatch"?"派发区":z==="review"?"验收区":z==="blocked"?"问题区":"休息区")+'</span><span class="dsc-role-task">'+esc(compact(task,58))+'</span></div>';}).join(""); flow.innerHTML=roles.map((r,i)=>{const z=zoneFor(r,snapshot); if(!["work","dispatch","review","blocked"].includes(z))return ""; const p=point(z,i); return '<line class="dsc-flow-line" x1="50" y1="6" x2="'+p[0]+'" y2="'+p[1]+'"></line>';}).join("");}
  function renderFeed(snapshot){const events=(snapshot.timeline||[]).slice(-3).reverse(), evidence=(snapshot.evidence||[]).slice(-3).reverse(), processes=(snapshot.processes||[]).filter(p=>p.status==="running").slice(0,3), cache=snapshot.cacheSummary||{}; feed.innerHTML='<div class="dsc-feed-card"><b>最新事件</b>'+(events.length?events.map(e=>'<span>'+esc(compact([roleLabel(e.role),e.tool,e.message||e.kind].filter(Boolean).join(" · "),70))+'</span>').join(""):'<span>等待事件</span>')+'</div><div class="dsc-feed-card"><b>产物 / Evidence</b>'+(evidence.length?evidence.map(e=>'<span><span class="dsc-feed-pill">'+esc(e.kind)+'</span>'+esc(compact(e.path||e.url||e.summary,64))+'</span>').join(""):'<span>暂无 evidence</span>')+'</div><div class="dsc-feed-card"><b>运行 / 缓存</b>'+(processes.length?processes.map(p=>'<span>'+esc(compact((p.url||p.command)+" · pid "+p.pid,70))+'</span>').join(""):'<span>暂无运行进程</span>')+(cache.cacheHitRate==null?'':'<span>缓存命中 '+esc(Math.round(cache.cacheHitRate*100))+'%</span>')+'</div>';}
  function renderDetail(snapshot,task){if(!task){detail.innerHTML='<div class="dsc-empty">选择任务查看证据、验收标准、角色 skill 和工具摘要。</div>';return;} const role=(snapshot.roles||[]).find(r=>r.role===task.assigneeRole)||{}, skill=(snapshot.generatedSkills||[]).find(s=>s.id===role.generatedSkillId||s.role===role.role)||{}, evid=(snapshot.evidenceBySubtask&&snapshot.evidenceBySubtask[task.id])||[], issue=task.blockedBy||role.blockedBy||"", raw=[...(role.toolResultSummary||[]),role.lastMessage,role.checkpoint].filter(Boolean).join("\\n"); detail.innerHTML='<div class="dsc-detail-title">'+esc(task.title)+'</div><div class="dsc-detail-line"><b>负责人</b> '+esc(roleLabel(task.assigneeRole))+' · '+esc(statusText(task.status))+'</div><div class="dsc-detail-line"><b>依赖</b> '+esc((task.dependencies||[]).join(", ")||"无")+'</div><div class="dsc-detail-line"><b>最近事件</b> '+esc(task.lastEvent||role.lastTool||"暂无")+'</div><details class="dsc-detail-section" open><summary>验收标准与 evidence</summary><div><b>验收：</b>'+esc((task.acceptanceCriteria||[]).join(" | ")||"暂无")+'\\n\\n<b>任务证据：</b>'+esc(evid.length?evid.map(e=>e.kind+":"+(e.path||e.url||e.summary)).join("\\n"):(task.evidence||[]).join(" | ")||"暂无")+'</div></details><details class="dsc-detail-section"><summary>角色专属 skill</summary><div>'+esc(skill.summary||role.generatedSkillSummary||"暂无 role-local skill 摘要")+'\\n\\n'+esc(skill.prompt||"")+'</div></details><details class="dsc-detail-section"><summary>职责与上下文范围</summary><div>'+esc(role.responsibility||"暂无")+'\\n\\n'+esc(role.contextScope||"暂无")+'</div></details>'+(issue?'<details class="dsc-detail-section" open><summary>错误/阻塞摘要</summary><div>'+esc(issue)+'</div></details>':'')+'<details class="dsc-detail-section"><summary>Checkpoint / 工具摘要 / 原始输出</summary><pre>'+esc(raw||"暂无。完整日志保留在本地 trace。")+'</pre></details>';}
  function render(snapshot){const tasks=snapshot.subtaskGraph||[], c=snapshot.completionSummary||{total:tasks.length,succeeded:0,skipped:0,running:0,needsReview:0,blocked:0,failed:0,percent:0}, mobile=snapshot.mobileSummary||{}; title.textContent=snapshot.overview?.objective||mobile.objective||"DeepSeekCode 多 Agent"; chips.innerHTML=chip(phaseText(snapshot.phase||snapshot.overview?.phase),snapshot.phase)+chip(approvalText(snapshot.approvalState?.status),snapshot.approvalState?.status)+chip(mobile.overallProgress||""); progressLabel.textContent=mobile.overallProgress?mobile.overallProgress+" 已完成":((c.succeeded||0)+(c.skipped||0))+"/"+(c.total||0)+" 已完成"; progress.style.width=Math.max(0,Math.min(100,c.percent||0))+"%"; next.textContent=mobile.nextStep||"等待下一步"; metrics.innerHTML=[["未完成",Math.max(0,(c.total||0)-(c.succeeded||0)-(c.skipped||0))],["执行中",c.running||0],["待验收",c.needsReview||0],["失败/阻塞",(c.blocked||0)+(c.failed||0)]].map(([l,v])=>'<div class="dsc-metric"><b>'+esc(v)+'</b><span>'+esc(l)+'</span></div>').join(""); const shown=tasks.filter(visible); list.innerHTML=shown.length?shown.map(t=>'<button class="dsc-task-row" type="button" data-id="'+esc(t.id)+'" aria-selected="'+(t.id===selected)+'"><span class="dsc-dot '+esc(t.status)+'"></span><span><span class="dsc-task-name">'+esc(t.title)+'</span><span class="dsc-task-meta">'+esc(roleLabel(t.assigneeRole))+' · '+esc((t.dependencies||[]).length?("依赖 "+t.dependencies.join(", ")):"无依赖")+'</span></span><span class="dsc-status">'+esc(statusText(t.status))+'</span></button>').join(""):'<div class="dsc-empty">当前没有任务数据。面板会自动追踪本项目 active workflow。</div>'; list.querySelectorAll("[data-id]").forEach(n=>n.addEventListener("click",()=>{selected=n.dataset.id||""; main.classList.add("dsc-detail-open"); renderDetail(snapshot,tasks.find(t=>t.id===selected)); list.querySelectorAll("[data-id]").forEach(x=>x.setAttribute("aria-selected",String(x.dataset.id===selected)));})); if(!selected&&tasks.length)selected=tasks[0].id; renderDetail(snapshot,tasks.find(t=>t.id===selected)); renderBoard(snapshot); renderStage(snapshot); renderFeed(snapshot); updated.textContent=snapshot.generatedAtMs?"更新于 "+new Date(snapshot.generatedAtMs).toLocaleTimeString():"等待 snapshot"; trace.href=api("/trace.jsonl");}
  function offline(message){if(disconnected)return; disconnected=true; document.body.classList.add("dsc-offline"); document.getElementById("dsc-offline-text").textContent=message||"本机 DeepSeekCode 已断开，页面保留最后一次状态。"; if(pollTimer)clearInterval(pollTimer);}
  async function tick(){if(disconnected)return; try{const res=await fetch(api("/snapshot"),{cache:"no-store"}); if(!res.ok)throw new Error("HTTP "+res.status); render(await res.json());}catch(e){offline("无法连接本机 DeepSeekCode："+(e&&e.message?e.message:e));}}
  function connect(){try{const u=new URL("/ws",location.href); u.protocol=u.protocol==="https:"?"wss:":"ws:"; u.searchParams.set("runId",panel.runId); u.searchParams.set("token",token); const ws=new WebSocket(u.toString()); ws.addEventListener("message",e=>{try{const m=JSON.parse(e.data); if(m.type==="serverShutdown")offline(m.message||"本机 DeepSeekCode 已关闭。");}catch{}}); ws.addEventListener("close",()=>offline("本机 DeepSeekCode 连接已断开。")); ws.addEventListener("error",()=>offline("本机 DeepSeekCode 连接异常。"));}catch{}}
  document.getElementById("dsc-collapse").addEventListener("click",()=>{const c=document.getElementById("dsc-console"), collapsed=!c.classList.contains("dsc-collapsed"); c.classList.toggle("dsc-collapsed",collapsed); document.documentElement.style.setProperty("--dsc-console-w",collapsed?"72px":"clamp(520px,40vw,760px)"); document.getElementById("dsc-collapse").textContent=collapsed?"展开":"收起";});
  filter.addEventListener("change",()=>tick());
  document.addEventListener("click",e=>{if(e.target===detail)main.classList.remove("dsc-detail-open");});
  setInterval(()=>document.querySelectorAll("button").forEach(b=>{const t=(b.textContent||"").trim(); if(["+","−","-","Layout","Settings"].includes(t)) b.classList.add("dsc-native-hidden");}),1200);
  connect(); tick(); pollTimer=setInterval(tick,1500);
})();
</script>`;
  return { style, markup, script };
}
