import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import PDFDocument from "pdfkit";
import { PDFDocument as PdfLibDocument } from "pdf-lib";
import type { z } from "zod";
import type { PlannedPdfActionSchema } from "../protocol/actions.js";
import { safeJoin } from "./pathSafety.js";

type PlannedPdfAction = z.input<typeof PlannedPdfActionSchema>;

export interface PdfArtifactResult {
  path: string;
  pageCount: number;
  checks: string[];
  previewPath?: string;
}

const DEFAULT_AUTHOR = "DeepSeekCode";
const A4_WIDTH = 595.28;
const PAGE_MARGIN = 54;
const CONTENT_WIDTH = A4_WIDTH - PAGE_MARGIN * 2;

export async function createPdfArtifact(root: string, input: PlannedPdfAction): Promise<PdfArtifactResult> {
  const target = ensureExtension(safeJoin(root, input.path), ".pdf");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const markdown = markdownFromInput(input);
  const fontPath = resolvePdfFont(root, input.font_path);
  const fontCheck = await writeMarkdownPdf(target, markdown, {
    title: input.title ?? titleFromMarkdown(markdown) ?? path.basename(target, ".pdf"),
    author: input.author ?? DEFAULT_AUTHOR,
    pageSize: input.page_size ?? "A4",
    fontPath,
  });
  const checks = ["pdf_written", fontCheck];
  const bytes = fs.readFileSync(target);
  const parsed = await PdfLibDocument.load(bytes, { ignoreEncryption: true });
  const pageCount = parsed.getPageCount();
  if (pageCount <= 0) throw new Error("Generated PDF has no pages.");
  checks.push(`pdf_pages=${pageCount}`);
  const previewPath = input.render_preview ? renderPreviewIfAvailable(target, root, checks) : undefined;
  return { path: target, pageCount, checks, previewPath };
}

function markdownFromInput(input: { markdown?: string; markdown_lines?: string[] }): string {
  return typeof input.markdown === "string"
    ? input.markdown
    : (input.markdown_lines ?? []).join("\n");
}

function titleFromMarkdown(markdown: string): string | undefined {
  return markdown.split(/\r?\n/).map((line) => line.trim()).find((line) => /^#\s+/.test(line))?.replace(/^#\s+/, "");
}

async function writeMarkdownPdf(
  target: string,
  markdown: string,
  options: { title: string; author: string; pageSize: "A4" | "LETTER"; fontPath?: string },
): Promise<string> {
  return await new Promise<string>((resolve, reject) => {
    let fontCheck = "font=Helvetica";
    const stream = fs.createWriteStream(target);
    const doc = new PDFDocument({
      size: options.pageSize,
      margin: PAGE_MARGIN,
      bufferPages: true,
      info: {
        Title: options.title,
        Author: options.author,
        Creator: "DeepSeekCode",
        Producer: "DeepSeekCode",
      },
    });
    stream.on("error", reject);
    doc.on("error", reject);
    doc.pipe(stream);
    fontCheck = applyPdfFont(doc, options.fontPath);
    addHeader(doc, options.title);
    renderMarkdown(doc, markdown || `# ${options.title}\n\nGenerated by DeepSeekCode.`);
    addPageNumbers(doc);
    doc.end();
    stream.once("finish", () => resolve(fontCheck));
  });
}

function applyPdfFont(doc: PDFKit.PDFDocument, fontPath?: string): string {
  if (!fontPath) {
    doc.font("Helvetica");
    return "font=Helvetica";
  }
  try {
    doc.registerFont("Body", fontPath);
    doc.font("Body");
    return `font=${path.basename(fontPath)}`;
  } catch (error) {
    doc.font("Helvetica");
    return `font_fallback=Helvetica reason=${compact(error instanceof Error ? error.message : String(error), 80)}`;
  }
}

function addHeader(doc: PDFKit.PDFDocument, title: string): void {
  doc
    .fontSize(9)
    .fillColor("#667085")
    .text("DeepSeekCode", PAGE_MARGIN, 28, { continued: true })
    .fillColor("#98A2B3")
    .text(`  ${compact(title, 72)}`, { align: "right" });
  doc
    .moveTo(PAGE_MARGIN, 44)
    .lineTo(doc.page.width - PAGE_MARGIN, 44)
    .strokeColor("#D0D5DD")
    .lineWidth(0.7)
    .stroke();
  doc.moveDown(1.2);
}

function renderMarkdown(doc: PDFKit.PDFDocument, markdown: string): void {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  let inCode = false;
  let codeLines: string[] = [];
  let table: string[][] = [];
  const flushCode = () => {
    if (!codeLines.length) return;
    ensureSpace(doc, 60);
    const text = codeLines.join("\n");
    const height = Math.min(220, doc.heightOfString(text, { width: CONTENT_WIDTH - 24 }) + 20);
    doc.roundedRect(PAGE_MARGIN, doc.y, CONTENT_WIDTH, height, 4).fill("#F2F4F7");
    doc.fillColor("#344054").fontSize(9).text(text, PAGE_MARGIN + 12, doc.y + 10, {
      width: CONTENT_WIDTH - 24,
      lineGap: 2,
    });
    doc.y += height + 10;
    codeLines = [];
  };
  const flushTable = () => {
    const rows = table.filter((row) => !row.every((cell) => /^:?-{3,}:?$/.test(cell.trim())));
    table = [];
    if (rows.length < 2) return;
    renderTable(doc, rows);
  };
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (/^```/.test(line.trim())) {
      if (inCode) {
        inCode = false;
        flushCode();
      } else {
        flushTable();
        inCode = true;
      }
      continue;
    }
    if (inCode) {
      codeLines.push(raw);
      continue;
    }
    if (line.includes("|") && line.trim().startsWith("|") && line.trim().endsWith("|")) {
      table.push(line.trim().slice(1, -1).split("|").map((cell) => cell.trim()));
      continue;
    }
    flushTable();
    const trimmed = line.trim();
    if (!trimmed) {
      doc.moveDown(0.35);
      continue;
    }
    const heading = /^(#{1,3})\s+(.+)$/.exec(trimmed);
    if (heading) {
      renderHeading(doc, heading[2]!, heading[1]!.length);
      continue;
    }
    const bullet = /^[-*]\s+(.+)$/.exec(trimmed);
    if (bullet) {
      renderParagraph(doc, `- ${bullet[1]}`, { bullet: true });
      continue;
    }
    const ordered = /^\d+[.)]\s+(.+)$/.exec(trimmed);
    if (ordered) {
      renderParagraph(doc, ordered[1]!, { bullet: true });
      continue;
    }
    renderParagraph(doc, trimmed);
  }
  flushTable();
  if (inCode) flushCode();
}

function renderHeading(doc: PDFKit.PDFDocument, text: string, level: number): void {
  const size = level === 1 ? 20 : level === 2 ? 15 : 12;
  ensureSpace(doc, level === 1 ? 76 : 52);
  doc.moveDown(level === 1 ? 0.8 : 0.45);
  doc.fillColor("#172033").fontSize(size).text(text, { width: CONTENT_WIDTH, lineGap: 3 });
  if (level === 1) {
    doc.moveTo(PAGE_MARGIN, doc.y + 4).lineTo(PAGE_MARGIN + 120, doc.y + 4).strokeColor("#2563EB").lineWidth(1.2).stroke();
    doc.moveDown(0.55);
  } else {
    doc.moveDown(0.25);
  }
}

function renderParagraph(doc: PDFKit.PDFDocument, text: string, options: { bullet?: boolean } = {}): void {
  ensureSpace(doc, 44);
  const x = options.bullet ? PAGE_MARGIN + 16 : PAGE_MARGIN;
  if (options.bullet) {
    doc.fillColor("#2563EB").fontSize(10).text("-", PAGE_MARGIN, doc.y, { width: 12 });
  }
  doc.fillColor("#344054").fontSize(10.5).text(stripInlineMarkdown(text), x, doc.y, {
    width: options.bullet ? CONTENT_WIDTH - 16 : CONTENT_WIDTH,
    lineGap: 4,
    align: "left",
  });
  doc.moveDown(0.3);
}

function renderTable(doc: PDFKit.PDFDocument, rows: string[][]): void {
  const columnCount = Math.max(...rows.map((row) => row.length), 1);
  const columnWidth = CONTENT_WIDTH / columnCount;
  const rowHeight = 28;
  ensureSpace(doc, Math.min(220, rows.length * rowHeight + 16));
  for (let rowIndex = 0; rowIndex < rows.length; rowIndex += 1) {
    const y = doc.y;
    const fill = rowIndex === 0 ? "#EAF2FF" : rowIndex % 2 ? "#FFFFFF" : "#F8FAFC";
    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, rowHeight).fill(fill).strokeColor("#D0D5DD").lineWidth(0.4).stroke();
    for (let columnIndex = 0; columnIndex < columnCount; columnIndex += 1) {
      doc.fillColor(rowIndex === 0 ? "#172033" : "#344054")
        .fontSize(rowIndex === 0 ? 9.5 : 9)
        .text(stripInlineMarkdown(rows[rowIndex]?.[columnIndex] ?? ""), PAGE_MARGIN + columnIndex * columnWidth + 8, y + 8, {
          width: columnWidth - 16,
          height: rowHeight - 10,
        });
    }
    doc.y = y + rowHeight;
    if (doc.y > doc.page.height - PAGE_MARGIN - rowHeight) doc.addPage();
  }
  doc.moveDown(0.6);
}

function addPageNumbers(doc: PDFKit.PDFDocument): void {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    doc.fillColor("#98A2B3").fontSize(8).text(
      `${i + 1 - range.start}/${range.count}`,
      PAGE_MARGIN,
      doc.page.height - 36,
      { width: CONTENT_WIDTH, align: "right" },
    );
  }
}

function ensureSpace(doc: PDFKit.PDFDocument, height: number): void {
  if (doc.y + height > doc.page.height - PAGE_MARGIN) {
    doc.addPage();
    addHeader(doc, String(doc.info.Title ?? "DeepSeekCode"));
  }
}

function stripInlineMarkdown(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");
}

function resolvePdfFont(root: string, requested?: string): string | undefined {
  const envFont = process.env.DEEPSEEKCODE_PDF_FONT;
  const candidates = [
    requested ? safeFontPath(root, requested) : undefined,
    envFont ? safeFontPath(root, envFont) : undefined,
    ...platformFontCandidates(),
  ].filter((candidate): candidate is string => Boolean(candidate));
  return candidates.find((candidate) => fs.existsSync(candidate));
}

function safeFontPath(root: string, value: string): string | undefined {
  if (!value.trim()) return undefined;
  return path.isAbsolute(value) ? value : safeJoin(root, value);
}

function platformFontCandidates(): string[] {
  if (process.platform === "win32") {
    const win = process.env.WINDIR ?? "C:\\Windows";
    return [
      path.join(win, "Fonts", "NotoSansSC-VF.ttf"),
      path.join(win, "Fonts", "Noto Sans SC (TrueType).otf"),
      path.join(win, "Fonts", "Deng.ttf"),
      path.join(win, "Fonts", "simhei.ttf"),
      path.join(win, "Fonts", "simsunb.ttf"),
      path.join(win, "Fonts", "msyh.ttf"),
      path.join(win, "Fonts", "msyh.ttc"),
      path.join(win, "Fonts", "simsun.ttc"),
    ];
  }
  if (process.platform === "darwin") {
    return [
      "/System/Library/Fonts/PingFang.ttc",
      "/System/Library/Fonts/STHeiti Light.ttc",
      "/Library/Fonts/Arial Unicode.ttf",
    ];
  }
  return [
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
  ];
}

function renderPreviewIfAvailable(pdfPath: string, root: string, checks: string[]): string | undefined {
  const probe = spawnSync("pdftoppm", ["-h"], { windowsHide: true, stdio: "ignore" });
  if (probe.error || probe.status === 127) {
    checks.push("preview_skipped=pdftoppm_missing");
    return undefined;
  }
  const outDir = path.join(root, "output", "pdf-preview");
  fs.mkdirSync(outDir, { recursive: true });
  const prefix = path.join(outDir, path.basename(pdfPath, ".pdf"));
  const result = spawnSync("pdftoppm", ["-png", "-f", "1", "-singlefile", pdfPath, prefix], {
    windowsHide: true,
    stdio: "ignore",
  });
  const preview = `${prefix}.png`;
  if (result.status === 0 && fs.existsSync(preview)) {
    checks.push("preview_rendered");
    return preview;
  }
  checks.push("preview_failed");
  return undefined;
}

function compact(value: string, max: number): string {
  const normalized = value.replace(/\s+/g, " ").trim();
  return normalized.length <= max ? normalized : `${normalized.slice(0, max - 3)}...`;
}

function ensureExtension(target: string, ext: ".pdf"): string {
  return target.toLowerCase().endsWith(ext) ? target : `${target}${ext}`;
}
